In [ ]:
import pandas as pd
import numpy as np
from scipy.stats import zscore

In [ ]:
dataset=pd.read_csv('Hitters.csv')
dataset

,Unnamed: 0,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,...,CRuns,CRBI,CWalks,League,Division,PutOuts,Assists,Errors,Salary,NewLeague
0,-Andy Allanson,293,66,1,30,29,14,1,293,66,...,30,29,14,A,E,446,33,20,NaN,A
1,-Alan Ashby,315,81,7,24,38,39,14,3449,835,...,321,414,375,N,W,632,43,10,475.0,N
2,-Alvin Davis,479,130,18,66,72,76,3,1624,457,...,224,266,263,A,W,880,82,14,480.0,A
3,-Andre Dawson,496,141,20,65,78,37,11,5628,1575,...,828,838,354,N,E,200,11,3,500.0,N
4,-Andres Galarraga,321,87,10,39,42,30,2,396,101,...,48,46,33,N,E,805,40,4,91.5,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,-Willie McGee,497,127,7,65,48,37,5,2703,806,...,379,311,138,N,E,325,9,3,700.0,N
318,-Willie Randolph,492,136,5,76,50,94,12,5511,1511,...,897,451,875,A,E,313,381,20,875.0,A
319,-Wayne Tolleson,475,126,3,61,43,52,6,1700,433,...,217,93,146,A,W,37,113,7,385.0,A
320,-Willie Upshaw,573,144,9,85,60,78,8,3198,857,...,470,420,332,A,E,1314,131,12,960.0,A
321,-Willie Wilson,631,170,9,77,44,31,11,4908,1457,...,775,357,249,A,W,408,4,3,1000.0,A

In [ ]:
dataset.describe

<bound method NDFrame.describe of             Unnamed: 0  AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  \
0       -Andy Allanson    293    66      1    30   29     14      1     293
1          -Alan Ashby    315    81      7    24   38     39     14    3449
2         -Alvin Davis    479   130     18    66   72     76      3    1624
3        -Andre Dawson    496   141     20    65   78     37     11    5628
4    -Andres Galarraga    321    87     10    39   42     30      2     396
..                 ...    ...   ...    ...   ...  ...    ...    ...     ...
317      -Willie McGee    497   127      7    65   48     37      5    2703
318   -Willie Randolph    492   136      5    76   50     94     12    5511
319    -Wayne Tolleson    475   126      3    61   43     52      6    1700
320     -Willie Upshaw    573   144      9    85   60     78      8    3198
321     -Willie Wilson    631   170      9    77   44     31     11    4908

     CHits  ...  CRuns  CRBI  CWalks  League Division PutOuts  Assists  \
0       66  ...     30    29      14       A        E     446       33
1      835  ...    321   414     375       N        W     632       43
2      457  ...    224   266     263       A        W     880       82
3     1575  ...    828   838     354       N        E     200       11
4      101  ...     48    46      33       N        E     805       40
..     ...  ...    ...   ...     ...     ...      ...     ...      ...
317    806  ...    379   311     138       N        E     325        9
318   1511  ...    897   451     875       A        E     313      381
319    433  ...    217    93     146       A        W      37      113
320    857  ...    470   420     332       A        E    1314      131
321   1457  ...    775   357     249       A        W     408        4

     Errors  Salary  NewLeague
0        20     NaN          A
1        10   475.0          N
2        14   480.0          A
3         3   500.0          N
4         4    91.5          N
..      ...     ...        ...
317       3   700.0          N
318      20   875.0          A
319       7   385.0          A
320      12   960.0          A
321       3  1000.0          A

[322 rows x 21 columns]>

In [ ]:
dataset.isnull().sum()

Unnamed: 0     0
AtBat          0
Hits           0
HmRun          0
Runs           0
RBI            0
Walks          0
Years          0
CAtBat         0
CHits          0
CHmRun         0
CRuns          0
CRBI           0
CWalks         0
League         0
Division       0
PutOuts        0
Assists        0
Errors         0
Salary        59
NewLeague      0
dtype: int64

In [ ]:
dataset["Salary"]=dataset["Salary"].fillna(dataset["Salary"].mean())
dataset

,Unnamed: 0,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,...,CRuns,CRBI,CWalks,League,Division,PutOuts,Assists,Errors,Salary,NewLeague
0,-Andy Allanson,293,66,1,30,29,14,1,293,66,...,30,29,14,A,E,446,33,20,535.925882,A
1,-Alan Ashby,315,81,7,24,38,39,14,3449,835,...,321,414,375,N,W,632,43,10,475.000000,N
2,-Alvin Davis,479,130,18,66,72,76,3,1624,457,...,224,266,263,A,W,880,82,14,480.000000,A
3,-Andre Dawson,496,141,20,65,78,37,11,5628,1575,...,828,838,354,N,E,200,11,3,500.000000,N
4,-Andres Galarraga,321,87,10,39,42,30,2,396,101,...,48,46,33,N,E,805,40,4,91.500000,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,-Willie McGee,497,127,7,65,48,37,5,2703,806,...,379,311,138,N,E,325,9,3,700.000000,N
318,-Willie Randolph,492,136,5,76,50,94,12,5511,1511,...,897,451,875,A,E,313,381,20,875.000000,A
319,-Wayne Tolleson,475,126,3,61,43,52,6,1700,433,...,217,93,146,A,W,37,113,7,385.000000,A
320,-Willie Upshaw,573,144,9,85,60,78,8,3198,857,...,470,420,332,A,E,1314,131,12,960.000000,A
321,-Willie Wilson,631,170,9,77,44,31,11,4908,1457,...,775,357,249,A,W,408,4,3,1000.000000,A

In [ ]:
dataset.drop("Unnamed: 0",axis=1,inplace=True)
dataset

,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,CHmRun,CRuns,CRBI,CWalks,League,Division,PutOuts,Assists,Errors,Salary,NewLeague
0,293,66,1,30,29,14,1,293,66,1,30,29,14,A,E,446,33,20,535.925882,A
1,315,81,7,24,38,39,14,3449,835,69,321,414,375,N,W,632,43,10,475.000000,N
2,479,130,18,66,72,76,3,1624,457,63,224,266,263,A,W,880,82,14,480.000000,A
3,496,141,20,65,78,37,11,5628,1575,225,828,838,354,N,E,200,11,3,500.000000,N
4,321,87,10,39,42,30,2,396,101,12,48,46,33,N,E,805,40,4,91.500000,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,497,127,7,65,48,37,5,2703,806,32,379,311,138,N,E,325,9,3,700.000000,N
318,492,136,5,76,50,94,12,5511,1511,39,897,451,875,A,E,313,381,20,875.000000,A
319,475,126,3,61,43,52,6,1700,433,7,217,93,146,A,W,37,113,7,385.000000,A
320,573,144,9,85,60,78,8,3198,857,97,470,420,332,A,E,1314,131,12,960.000000,A
321,631,170,9,77,44,31,11,4908,1457,30,775,357,249,A,W,408,4,3,1000.000000,A

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(sparse=False)
encoded=encoder.fit_transform(dataset[["League","Division","NewLeague"]])
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out(["League","Division","NewLeague"]))
encoded_df

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

     League_A  League_N  Division_E  Division_W  NewLeague_A  NewLeague_N
0         1.0       0.0         1.0         0.0          1.0          0.0
1         0.0       1.0         0.0         1.0          0.0          1.0
2         1.0       0.0         0.0         1.0          1.0          0.0
3         0.0       1.0         1.0         0.0          0.0          1.0
4         0.0       1.0         1.0         0.0          0.0          1.0
..        ...       ...         ...         ...          ...          ...
317       0.0       1.0         1.0         0.0          0.0          1.0
318       1.0       0.0         1.0         0.0          1.0          0.0
319       1.0       0.0         0.0         1.0          1.0          0.0
320       1.0       0.0         1.0         0.0          1.0          0.0
321       1.0       0.0         0.0         1.0          1.0          0.0

[322 rows x 6 columns]

In [ ]:
dataset.drop(["League","Division","NewLeague"],axis=1,inplace=True)
dataset

,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,CHmRun,CRuns,CRBI,CWalks,PutOuts,Assists,Errors,Salary
0,293,66,1,30,29,14,1,293,66,1,30,29,14,446,33,20,535.925882
1,315,81,7,24,38,39,14,3449,835,69,321,414,375,632,43,10,475.000000
2,479,130,18,66,72,76,3,1624,457,63,224,266,263,880,82,14,480.000000
3,496,141,20,65,78,37,11,5628,1575,225,828,838,354,200,11,3,500.000000
4,321,87,10,39,42,30,2,396,101,12,48,46,33,805,40,4,91.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,497,127,7,65,48,37,5,2703,806,32,379,311,138,325,9,3,700.000000
318,492,136,5,76,50,94,12,5511,1511,39,897,451,875,313,381,20,875.000000
319,475,126,3,61,43,52,6,1700,433,7,217,93,146,37,113,7,385.000000
320,573,144,9,85,60,78,8,3198,857,97,470,420,332,1314,131,12,960.000000
321,631,170,9,77,44,31,11,4908,1457,30,775,357,249,408,4,3,1000.000000

In [ ]:
dataset=pd.concat([dataset,encoded_df],axis=1)
dataset

,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,CHmRun,...,PutOuts,Assists,Errors,Salary,League_A,League_N,Division_E,Division_W,NewLeague_A,NewLeague_N
0,293,66,1,30,29,14,1,293,66,1,...,446,33,20,535.925882,1.0,0.0,1.0,0.0,1.0,0.0
1,315,81,7,24,38,39,14,3449,835,69,...,632,43,10,475.000000,0.0,1.0,0.0,1.0,0.0,1.0
2,479,130,18,66,72,76,3,1624,457,63,...,880,82,14,480.000000,1.0,0.0,0.0,1.0,1.0,0.0
3,496,141,20,65,78,37,11,5628,1575,225,...,200,11,3,500.000000,0.0,1.0,1.0,0.0,0.0,1.0
4,321,87,10,39,42,30,2,396,101,12,...,805,40,4,91.500000,0.0,1.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,497,127,7,65,48,37,5,2703,806,32,...,325,9,3,700.000000,0.0,1.0,1.0,0.0,0.0,1.0
318,492,136,5,76,50,94,12,5511,1511,39,...,313,381,20,875.000000,1.0,0.0,1.0,0.0,1.0,0.0
319,475,126,3,61,43,52,6,1700,433,7,...,37,113,7,385.000000,1.0,0.0,0.0,1.0,1.0,0.0
320,573,144,9,85,60,78,8,3198,857,97,...,1314,131,12,960.000000,1.0,0.0,1.0,0.0,1.0,0.0
321,631,170,9,77,44,31,11,4908,1457,30,...,408,4,3,1000.000000,1.0,0.0,0.0,1.0,1.0,0.0

In [ ]:
z_scores = np.abs(zscore(dataset))
outliers = np.where(z_scores > 3)
outliers

(array([ 30,  32,  73,  73,  80,  82,  82,  84,  96, 100, 112, 113, 114,
        121, 136, 163, 163, 179, 179, 180, 189, 217, 229, 235, 236, 236,
        236, 236, 236, 248, 249, 249, 249, 249, 260, 272, 274, 276, 278,
        292, 302, 302, 302, 302, 302, 306, 310, 313, 315, 320]),
 array([12, 13,  9, 12,  9, 13, 16, 16, 16, 16, 16, 13,  9,  9,  2,  9, 16,
        13, 16, 13, 13, 16, 16, 13,  6,  7,  8, 10, 12,  3,  9, 10, 11, 12,
        15, 13, 13, 15, 13, 12,  6,  7,  8,  9, 11, 11, 13,  5, 13, 13]))

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,accuracy_score
x=dataset.drop("Salary",axis=1)
y=dataset["Salary"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import Lasso
lasso_model=Lasso(alpha=0.1)
lasso_model.fit(x_train,y_train)
lasso_model.score(x_test,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.103e+07, tolerance: 4.096e+03
  model = cd_fast.enet_coordinate_descent(

0.3361361681321474

In [ ]:
from sklearn.linear_model import Ridge
ridge_model=Ridge(alpha=0.1)
ridge_model.fit(x_train,y_train)
ridge_model.score(x_test,y_test)

0.3368917817195831

In [ ]:
from sklearn.linear_model import LinearRegression
linear_model=LinearRegression()
linear_model.fit(x_train,y_train)
linear_model.score(x_test,y_test)

0.3368958572786419